# 선택 가능한 백엔드: openai | supertonic2
backend: openai

# 공통 출력 설정
output_channels: 2
output_device_name:
  - 14
  - 15

openai:
  model_name: gpt-4o-mini-tts
  output_sample_rate: 24000
  voice:
    play_default: shimmer

supertonic2:
  auto_download: true
  sample_rate: 44100
  lang: ko
  voice_style: F1
  total_step: 5
  speed: 1.05
  max_chunk_length: 120
  silence_duration: 0.3
